### ISSUE TITLE
Unable to add Neato D10

### ISSUE THREAD

**Issue by forvelin** [BenjaminPaap/home-assistant-myneato#1]
Hi, thanks for the integration, but I get the error below from HA when I try to add my device :

```

Logger: homeassistant.config_entries
Source: util/async_.py:168
First occurred: 1:49:57 AM (2 occurrences)
Last logged: 1:52:20 AM
Error setting up entry MyNeato for myneato

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/myneato/__init__.py", line 59, in async_setup_entry
    await hub.update_floorplans()
  File "/config/custom_components/myneato/hub.py", line 31, in update_floorplans
    for floorplan in self.account.floorplans:
  File "/usr/local/lib/python3.10/site-packages/pyneato/account.py", line 96, in floorplans
    self.refresh_floorplans()
  File "/usr/local/lib/python3.10/site-packages/pyneato/account.py", line 159, in refresh_floorplans
    self.get_floorplan(robot)
  File "/usr/local/lib/python3.10/site-packages/pyneato/account.py", line 164, in get_floorplan
    resp = self._session.get("/robots/%s/floorplans"%robot.id)
  File "/usr/local/lib/python3.10/site-packages/pyneato/session.py", line 99, in get
    response = requests.get(url, headers=headers, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1293, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 219, in putrequest
    return _HTTPConnection.putrequest(self, method, url, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 180, in protected_loop_func
    check_loop(func, strict=strict)
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 168, in check_loop
    raise RuntimeError(
RuntimeError: Blocking calls must be done in the executor or a separate thread; Use `await hass.async_add_executor_job()`; at custom_components/myneato/hub.py, line 31: for floorplan in self.account.floorplans:

```
Not sure if it is a bug or am I using wrong version of HA.

**Comment by forvelin** [comment]
Closing, found out that after first mapping, the integration worked, at least it brought battery level. At least a one cleaning needed before integration works.

**Comment by mmacey54** [comment]
Similar issue here but still not working after a few cleaning runs. So you added the integration and got this error, but after performing a cleaning run it started working? Nothing else special?
