### ISSUE TITLE
RobotActionEnum missing state 'cleaning_standby'

### ISSUE THREAD

**Issue by dchote** [BenjaminPaap/home-assistant-myneato#14]
I just added this integration while my robot was mid-clean and it seems to error out on a missing state `cleaning_standby`.  I can submit a PR if that would be preferred.

```
myneato: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 575, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 961, in async_device_update
    await hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/myneato/vacuum.py", line 156, in update
    self._state = self.robot.state
                  ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyneato/robot.py", line 316, in state
    return self.get_state()
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyneato/robot.py", line 262, in get_state
    RobotActionEnum(json["action"]),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 712, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 1135, in __new__
    raise ve_exc
ValueError: 'cleaning_standby' is not a valid RobotActionEnum
```

**Comment by BenjaminPaap** [comment]
I would love to see a PR for that
