### ISSUE TITLE
Error setting up entry MyNeato for myneato

### ISSUE THREAD

**Issue by mmacey54** [BenjaminPaap/home-assistant-myneato#4]
Thank you very much for your work on this! However, I'm struggling to add my D10. After adding the integration and logging in to my account I get this error and am unable to add any entities:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/myneato/__init__.py", line 59, in async_setup_entry
    await hub.update_floorplans()
  File "/config/custom_components/myneato/hub.py", line 32, in update_floorplans
    await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/pyneato/floorplan.py", line 76, in refresh_tracks
    cleaning_mode = CleaningModeEnum(track["cleaning_mode"])
  File "/usr/local/lib/python3.10/enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.10/enum.py", line 710, in __new__
    raise ve_exc
ValueError: 'auto' is not a valid CleaningModeEnum

Anyone have any thoughts? Am I missing a step? Another user mentioned a similar issue that corrected itself after a cleaning run but unfortunately this hasn't worked for me.

**Comment by BenjaminPaap** [comment]
Thanks for your report @mmacey54. I was able to reproduce this with my D10 and published a new release.

**Comment by mmacey54** [comment]
> Thanks for your report @mmacey54. I was able to reproduce this with my D10 and published a new release.

Awesome, it's working now. Thanks so much for your work!
